version: "3.9"

services:
  backend1:
    build: ./backend
    container_name: backend1
    restart: always
    networks:
      - app-network

  backend2:
    build: ./backend
    container_name: backend2
    restart: always
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
